### ISSUE TITLE
getting the attached 2 error dialogues tryin to launch from XRM Toolbox

### ISSUE THREAD

**Issue by lrogers-AriaConsulting** [yesadahmed/PowerAutomateManagerDocs#1]
After connecting to my SBX instance of 365 CE, I'm getting the attached error dialogues. 
![Error1](https://user-images.githubusercontent.com/49916413/126524706-985f853e-6bf3-44ae-9299-baff43e4175c.png)
![Error2](https://user-images.githubusercontent.com/49916413/126524708-b23ba6f1-336a-45fa-a528-2ab85e09f13e.png)

**Comment by yesadahmed** [comment]
Hi AriaConsulting,
first thanks for using the tool :)

From the error you posted, it looks you are using quite an old version of Microsoft.CrmSdk.XrmTooling, assembly.
The minimum version which supports the method ExecuteCrmWebRequest is **9.0.2.3**.

Please make sure you update to the latest version of XrmToolBox so you have updated NuGet references for
Microsoft.CrmSdk.XrmTooling

Meanwhile here are the minimum references for this Plugin

1. Microsoft.Identity.Client (>= 4.22.0)
2. XrmToolBox (>=1.2020.6.40)

I hope this helps, 

Regards
Adnan Samuel

**Comment by parvezghumra** [comment]
Hi @yesadahmed 

I am experiencing exactly the same errors mentioned above by @lrogers-AriaConsulting despite using the latest version of XrmToolbox and the plugin.

Please advise further

**Comment by yesadahmed** [comment]
Are you using **OAUTH** Connection to connect to Dynamic365?
If this is the case please refer to the documentation page.

Please also check the version in  GAC of your local machine, is it the latest?

**Comment by StephaneSeguin** [comment]
I have the same issue. I'm on the latest version of Xrmtool box.

I have connected using Oauth. Followed the documentation.

Same probleme

**Comment by yesadahmed** [comment]
I have uploaded new version of PowerAutomateCloudManger  1.0.0.01
This version does not contain ExecuteCrmWebRequest .

**Comment by yesadahmed** [comment]
I hope everything is good with the new version,
closing the issue
